### PR TITLE
Add bypass_hwid setting to panel & upgrade flask

### PR DESCRIPTION
**Pull request by Kaimi8**
I also upgraded the flask version because the app wouldn't start without it. I tested around a few routes and skimmed through the changes and it doesn't seem to have any affect on the panel.

https://stackoverflow.com/questions/71189819/python-docker-importerror-cannot-import-name-json-from-itsdangerous
https://stackoverflow.com/a/71213267

image

### CODE REVIEW

**Review by lenforiee — CHANGES_REQUESTED** [review]
I believe we use SQL bools which means you’ll have to change all True/False to 1/0

Eg line 922 in functions.py and values in html

**Comment by Kaimi8** [comment]
In your database, what does bypass_hwid look like?
image

It looks like this for me. If you try to insert a string through, you get an error. That's why this line converts it into a python boolean:
https://github.com/RealistikOsu/RealistikPanel/pull/69/commits/8fa91a52e46bc012beb6a9070ad3a235ce5719af#diff-52c0e4b6841bd4f4a02e448335402ac42d01be84113d64602e93d56b9ac606efR921

This is how bypass_hwid is stored in my db:
image
https://github.com/RealistikOsu/USSR/blob/4f93e80bb88732129f13a11c994142de034be203/extras/db.sql#L689

**Comment by RealistikDash** [comment]
It is likely that the connector automatically converts the bool into an integer

**Comment by lenforiee** [comment]
our type in database is tinyint so it shouldn’t accept strings, i would still like you to change it to int bools for database consistency

**Comment by lenforiee** [comment]
merged, thanks!

**Pull request merged**
